### ISSUE TITLE
Empty LoginView

### ISSUE THREAD

**Issue by GilWu** [vaadin-learning-center/spring-secured-vaadin#2]
Hi,

it seems there is some code missing in the LoginView class. 
To have a functional application, it would be perfect to add the missing code.

Best,
Gilwu

**Comment by paulroemer** [comment]
Hey GilWu,

what do you mean? Are you talking about the master branch? Well, this one does not contain any login view code, you are right. But instead you should check out the branches and decide which login view implementation and approach you like. Check the readme.

**Comment by GilWu** [comment]
Ahhhh, sorry.
